[tool.poetry]
name = "jackmesh"
version = "0.1.2"
description = "Python-based utility for managing Jack audio server connections with simple TOML config files."
license = "GNU GPL v3"
authors = ["omnitonal.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
jackmesh = "jackmesh.jackmesh:main"