[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hirmeos_google_books"
version = "0.0.1"
authors = [
  { name="Cristian Garcia", email="cristian.garcia@ubiquitypress.com" },
]
description = "Functions required by the hirmeos-google-books-driver"
readme = "README.rst" 
requires-python = ">=3.10"
dependencies = [
  "selenium >= 4.0",
  "webdriver_manager >= 4.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
