[tool.poetry]
name = "translator-cli"
version = "0.3.12"
description = "A tool for translating texts between different languages"
authors = ["Sergio Puche Garc√≠a <serpucga@inf.upv.es>"]
readme = "README.md"
packages = [{include = "translator", from = "."}]

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.6.0"
multiprocess = "^0.70.13"
requests = "^2.28.1"
translators = "^5.8.3"
deepl = "^1.15.0"
chatgpt-klient = "^0.2.3"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.0.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
