[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "blackjack-amiyuki7"
authors = [{name = "Alexander Xie", email = "amiyuki788@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
requires-python = ">=3.10"
dependencies = [
	"pygame>=2.5.1",
	"loguru>=0.7.2"
]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/amiyuki7/blackjack"

[tool.flit.module]
name = "blackjack"

[tool.black]
line-length = 100
target-version = ["py311"]
