[tool.poetry]
name = "litestar-cdk-lib"
version = "0.1.1"
description = ""
authors = ["kjaye <26447239+KristaBliss@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aws-cdk-lib = ">2.0,<3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
