[tool.poetry]
name = "swagchain"
version = "0.0.3"
description = ""
authors = ["Oscar Bahamonde <oscar.bahamonde.dev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aiofauna = "^0.1.99"
openai = "^0.28.0"
tiktoken = "^0.5.1"
numpy = "^1.25.2"
lxml = "^4.9.3"
bs4 = "^0.0.1"
jinja2 = "^3.1.2"


[tool.poetry.group.dev.dependencies]
sphinx = {extras = ["sitemap"], version = "^7.2.6"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
