[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "toxinet"
version = "0.0.1"
authors = [
  { name="Arpan Mukherjee, An Su, and Krishna Rajan", email="krajan3@buffalo.edu" },
]
description = "Identifying structural motif with SMILES"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/MatInfoUB/VisualTox"
"Bug Tracker" = "https://github.com/mcgomez16/VisualTox_copy"