[tool.poetry]
name = "cognite-ai"
version = "0.1.0"
description = "A set of tools for working with Cognite Data Fusion in Python"
authors = ["Anders Hafreager <andershaf@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "cognite"}]

[tool.poetry.dependencies]
python = ">=3.9"


[tool.poetry.group.dev.dependencies]
twine = "^4.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
