[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "multicfg"
version = "0.0.5"
authors = [
  { name="pyAxolotl", email="abdellatifzied.saada@gmail.com" },
]
description = "Python package to read config from different sources: config files, command line, ..."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]