[project]
name = "mongoday"
version = "0.0.3"
authors = [
  { name = "Abrar Arshad", email = "abrar.arshad01@gmail.com" },
]
description = "A simple way to create documents in MongoDB"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/abrararshad/mongoday"
"Bug Tracker" = "https://github.com/abrararshad/mongoday/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
