[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sysnet-citesdoc"
version = "1.0.0.003"
authors = [
  { name="Radim Jaeger", email="rjaeger@sysnet.cz" },
]
description = "CITES Documents data connector REST API 1.0.0"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content"
]

[project.urls]
"Homepage" = "https://github.com/SYSNET-CZ/swagger/tree/main/clients/citesdoc"
