[tool.poetry]
name = "pywidgets"
version = "0.1.0"
description = ""
authors = ["Leo <jafee201153@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pyside6 = "^6.5.2"
matplotlib = "^3.8.0"


[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
twine = "^4.0.2"
wheel = "^0.41.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
