[tool.poetry]
name = "quicksift"
version = "0.1.3"
description = ""
authors = ["chrisaddy <chris.william.addy@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "quicksift"}]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.1.0"
polars = "^0.19.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
