[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "saoovqe"
version = "0.1.2"
authors = [
    { name="Martin Beseda", email="martinbeseda@seznam.cz" },
    {name="Silvie Illésová", email="silvie.illesova@seznam.cz"},
    {name="Saad Yalouz", email="yalouzsaad@gmail.com"},
    {name="Bruno Senjean", email="bsenjean@gmail.com"}
]
description = "SA-OO-VQE method implemented via Qiskit library"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
]
dependencies=[
    "qiskit>=0.43.0",
    "qiskit-nature>=0.6.2",
    "numpy>=1.22.0,<1.24.0",
    "deprecated>=1.2.14",
    "mendeleev>=0.13.1",
    "scipy>=1.10.1",
    "sympy>=1.11.1",
    "setuptools>=67.8.0",
    "lxml>=4.9.2",
    "nlopt",
    "ipython",
    "jupyter",
    "pygments",
    "scikit-learn>=1.2.2",
    "icecream>=2.1.3",
    "pytest>=7.3.1"
]

[project.urls]
"Homepage" = "https://gitlab.com/MartinBeseda/sa-oo-vqe-qiskit.git"
"Documentation" = "https://sa-oo-vqe-qiskit.readthedocs.io/en/latest/"
