[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "excel-worker"
version = "0.0.2"
authors = [
    { name = "John" },
]
description = "A small excel package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "pandas<2",
    "XlsxWriter==3.0.1",
]

[project.optional-dependencies]
dev = [
    "black",
    "isort"
]

[tool.black]
line-length = 90

[tool.isort]
profile = "black"
line_length = 90
multi_line_output = 3
skip_gitignore = true
src_paths = ["src/"]
